/** @type {import('tailwindcss').Config} */
module.exports = {
  mode: "jit",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        costumeYellow: "#FFCB05",
        costumeBlue: "#3D7DCA",
        costumeNavyBlue: "#003A70",
        costumeRed: "#E4000F",
        normal: "#A8A77A",
        normal2: "#dcdcca",
        fire: "#EE8130",
        fire2: "#F6C097",
        water: "#6390F0",
        water2: "#B1C7F7",
        electric: "#F7D02C",
        electric2: "#fcecab",
        grass: "#7AC74C",
        grass2: "#cae9b7",
        ice: "#96D9D6",
        ice2: "#d5f0ef",
        fighting: "#C22E28",
        fighting2: "#eca6a3",
        poison: "#A33EA1",
        poison2: "#e0acdf",
        ground: "#E2BF65",
        ground2: "#f3e5c1",
        flying: "#A98FF3",
        flying2: "#ddd2fa",
        psychic: "#F95587",
        psychic2: "#fdbbcf",
        bug: "#A6B91A",
        bug2: "#e5f096",
        rock: "#B6A136",
        rock2: "#e6dcaa",
        ghost: "#735797",
        ghost2: "#c7bad7",
        dragon: "#6F35FC",
        dragon2: "#c5aefe",
        dark: "#705746",
        dark2: "#cdbbae",
        steel: "#B7B7CE",
        steel2: "#e2e2eb",
        fairy: "#D685AD",
        fairy2: "#efcede",
      },
    },
  },
  plugins: [],
};
